import json
import math
import requests
import time

# --- Constants ---
# Perimeter Vertices (Extracted from analyze_perimeter_sides.py output)
V1 = [-75.25695083552709, -15.165498334382889] # NE
V2 = [-75.26825393885237, -15.172534472456562] # NW
V3 = [-75.23798892224755, -15.197477563030073] # S

# Output File (Isolated)
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_3d.js'

# Config
GRID_SPACING_METERS = 50 # High Resolution

# --- Helpers ---
def get_elevation_batch(locations):
    """
    Fetch elevations from Open-Meteo for a list of (lat, lon).
    API limits: Check documentation. Often chunks of locations are better.
    """
    base_url = "https://api.open-meteo.com/v1/elevation"
    elevations = []
    
    # Process in chunks to respect URL length / API limits
    CHUNK_SIZE = 100 
    
    print(f"Fetching elevation for {len(locations)} points...")
    
    for i in range(0, len(locations), CHUNK_SIZE):
        chunk = locations[i:i+CHUNK_SIZE]
        lats = [f"{p[1]:.6f}" for p in chunk]
        lons = [f"{p[0]:.6f}" for p in chunk]
        
        url = f"{base_url}?latitude={','.join(lats)}&longitude={','.join(lons)}"
        
        while True:
            try:
                resp = requests.get(url)
                data = resp.json()
                
                if 'elevation' in data:
                    elevations.extend(data['elevation'])
                    print(f"  Chunk {i}: OK")
                    break # Success
                elif 'error' in data and 'limit' in str(data.get('reason', '')).lower():
                    print("  Rate limit hit. Waiting 60s...")
                    time.sleep(60)
                    continue # Retry
                else:
                    print(f"  Error in chunk {i}: {data}")
                    elevations.extend([0]*len(chunk))
                    break # Skip batch on other errors
                
            except Exception as e:
                print(f"Request failed: {e}")
                time.sleep(5)
                # Simple retry logic could define separate counter, here just break to avoid inf loop on net error
                elevations.extend([0]*len(chunk))
                break
            
        time.sleep(2) # Increased polite delay
            
    return elevations

def point_in_triangle(pt, v1, v2, v3):
    """
    Barycentric coordinate technique to check if pt is in triangle v1,v2,v3
    pt, v1, v2, v3 are [lon, lat]
    """
    def sign(p1, p2, p3):
        return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])

    d1 = sign(pt, v1, v2)
    d2 = sign(pt, v2, v3)
    d3 = sign(pt, v3, v1)

    has_neg = (d1 < 0) or (d2 < 0) or (d3 < 0)
    has_pos = (d1 > 0) or (d2 > 0) or (d3 > 0)

    return not (has_neg and has_pos)

def add_meters_to_coords(lat, lon, dy_meters, dx_meters):
    """
    Approximate offset.
    1 deg lat ~= 111132.92 m
    1 deg lon ~= 111412.84 * cos(lat) m
    """
    r_earth = 6378137
    pi = math.pi
    
    new_lat = lat + (dy_meters / r_earth) * (180 / pi)
    new_lon = lon + (dx_meters / r_earth) * (180 / pi) / math.cos(lat * pi/180)
    
    return [new_lon, new_lat]

def main():
    # 1. Define Bounding Box
    lons = [V1[0], V2[0], V3[0]]
    lats = [V1[1], V2[1], V3[1]]
    
    min_lon, max_lon = min(lons), max(lons)
    min_lat, max_lat = min(lats), max(lats)
    
    # 2. Generate Grid Points
    # We scan from Top-Left (NW) to Bottom-Right (SE) roughly
    # Actually, let's just grid the bbox and filter
    
    # Calculate step usage roughly in degrees
    # 1 deg lat ~ 111km -> 50m = 0.00045 deg
    
    lat_step = (50 / 111132) 
    # lon step depends on lat, use average lat
    avg_lat = (min_lat + max_lat) / 2
    lon_step = (50 / (111320 * math.cos(math.radians(avg_lat))))
    
    print(f"Grid Steps deg: Lat {lat_step:.6f}, Lon {lon_step:.6f}")
    
    grid_points = []
    
    curr_lat = max_lat
    while curr_lat >= min_lat:
        curr_lon = min_lon
        while curr_lon <= max_lon:
            pt = [curr_lon, curr_lat]
            if point_in_triangle(pt, V1, V2, V3):
                grid_points.append(pt)
            curr_lon += lon_step
        curr_lat -= lat_step
        
    print(f"Generated {len(grid_points)} candidate points inside triangle.")
    
    if not grid_points:
        print("No points found. Check logic.")
        return

    # 3. Fetch Data
    elevations = get_elevation_batch(grid_points)
    
    # 4. Format for Plotly (x, y, z arrays)
    # Plotly Mesh3D or Scatter3D
    x_coords = [p[0] for p in grid_points] # Lon
    y_coords = [p[1] for p in grid_points] # Lat
    z_coords = elevations
    
    # Create JS file
    js_content = f"""
// Auto-generated by generate_terrain_mesh.py
// Isolated 3D Terrain Data
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(x_coords)},
    y: {json.dumps(y_coords)},
    z: {json.dumps(z_coords)},
    type: 'mesh3d',
    intensity: {json.dumps(z_coords)},
    colorscale: 'Earth'
}};
"""
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Saved {len(grid_points)} points to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
