const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00061",
        "name": "MSC ANISHA R.",
        "eta": "29/01/2026 13:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "PA - RODMAN",
        "origin_country": "PANAMA",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 281.03,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-36",
        "name": "SEAWAYS KOLBERG",
        "eta": "29/01/2026 01:00:00",
        "agency": "COSMOS",
        "origin_port": "PA - BALBOA",
        "origin_country": "PANAMA",
        "terminal": "PENTA TANKS",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "ISLAS MARSHALL",
        "length": 183,
        "beam": 32.2,
        "dwt": 44999.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-64",
        "name": "ARSOS",
        "eta": "29/01/2026 05:00:00",
        "agency": "CITIKOLD",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "CHIPRE",
        "length": 166.15,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-61",
        "name": "MSC ANISHA R.",
        "eta": "29/01/2026 20:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 281.03,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00274",
        "name": "EL MARQUEZ",
        "eta": "29/01/2026 06:00:00",
        "agency": "DOLMAR",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "BAHIA",
        "etb": "01/01/0001 00:00:00",
        "type": "PESQUERO",
        "flag": "PANAMA",
        "length": 41.48,
        "beam": 10.15,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00266",
        "name": "AFRICAN BAZA",
        "eta": "29/01/2026 08:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "AR - SAN LORENZO",
        "origin_country": "ARGENTINA",
        "terminal": "APM TERMINALS",
        "etb": "29/01/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "BAHAMAS",
        "length": 199.98,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00244",
        "name": "LORI",
        "eta": "29/01/2026 08:30:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "29/01/2026 10:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 228,
        "beam": 37.3,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00189",
        "name": "MSC CAROLE",
        "eta": "29/01/2026 09:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "PE - PISCO",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "29/01/2026 12:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 328.46,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00288",
        "name": "DU AN CHENG",
        "eta": "29/01/2026 11:00:00",
        "agency": "COSCO",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "HONG KONG",
        "length": 177.5,
        "beam": 28.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00257",
        "name": "EVROTAS",
        "eta": "29/01/2026 11:00:00",
        "agency": "RENADSA",
        "origin_port": "US - CORPUS CHRISTI",
        "origin_country": "ESTADOS UNIDOS",
        "terminal": "LA PAMPILLA",
        "etb": "-",
        "type": "BUQUE PETROLERO PARA CRUDOS",
        "flag": "LIBERIA",
        "length": 204.19,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00177",
        "name": "ONE SPARKLE",
        "eta": "29/01/2026 13:00:00",
        "agency": "MERCATOR",
        "origin_port": "GT - PUERTO QUETZAL",
        "origin_country": "GUATEMALA",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "SINGAPORE",
        "length": 335,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00302",
        "name": "GOLDEN GLORY",
        "eta": "29/01/2026 14:00:00",
        "agency": "AGUNSA PERU",
        "origin_port": "PE - CHIMBOTE",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "31/01/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.98,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00251",
        "name": "MORNING LINDA",
        "eta": "29/01/2026 14:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CL - IQUIQUE",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "-",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "PANAMA",
        "length": 232.37,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00275",
        "name": "MORNING SPARROW",
        "eta": "29/01/2026 15:00:00",
        "agency": "COSMOS",
        "origin_port": "CL - CORONEL",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "01/01/0001 00:00:00",
        "type": "BUQUE TANQUE",
        "flag": "LIBERIA",
        "length": 185.99,
        "beam": 32.23,
        "dwt": 49997.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-235",
        "name": "MAERSK JALAN",
        "eta": "29/01/2026 05:00:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "PE - PAITA",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "SINGAPORE",
        "length": 222.15,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-224",
        "name": "AS CASPRIA",
        "eta": "29/01/2026 07:00:00",
        "agency": "COSMOS",
        "origin_port": "PE - PAITA",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 225.2,
        "beam": 31,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-247",
        "name": "MANTARO",
        "eta": "29/01/2026 09:30:00",
        "agency": "RENADSA",
        "origin_port": "PE - MOLLENDO",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 183,
        "beam": 32.2,
        "dwt": 51393.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-217",
        "name": "STAR ROTTERDAM",
        "eta": "29/01/2026 15:00:00",
        "agency": "CANOPUS",
        "origin_port": "PE - PISCO",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2025-3551",
        "name": "PORTO",
        "eta": "29/01/2026 15:00:00",
        "agency": "ISS MARINE",
        "origin_port": "PA - BALBOA",
        "origin_country": "PANAMA",
        "terminal": "BAHIA",
        "etb": "",
        "type": "REMOLCADOR",
        "flag": "PERU",
        "length": 37.06,
        "beam": 11.58,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-204",
        "name": "EVER LUNAR",
        "eta": "29/01/2026 16:00:00",
        "agency": "TPP",
        "origin_port": "CL - VALPARAISO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "TAIWAN, PROVINCIA DE CHINA",
        "length": 334.8,
        "beam": 45.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-219",
        "name": "KOTA CANTIK",
        "eta": "29/01/2026 18:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "HONG KONG",
        "length": 301.32,
        "beam": 40,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-288",
        "name": "DU AN CHENG",
        "eta": "29/01/2026 19:00:00",
        "agency": "COSCO",
        "origin_port": "EC - PUERTO BOLIVAR",
        "origin_country": "ECUADOR",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "HONG KONG",
        "length": 177.5,
        "beam": 28.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-189",
        "name": "MSC CAROLE",
        "eta": "29/01/2026 20:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "PE - PAITA",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 328.46,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-251",
        "name": "MORNING LINDA",
        "eta": "29/01/2026 23:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "KR - PYEONGTAEK",
        "origin_country": "COREA DEL SUR",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "PANAMA",
        "length": 232.37,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00043",
        "name": "SEA VOYAGER",
        "eta": "29/01/2026 07:00:00",
        "agency": "SERPAC",
        "origin_port": "KR - DONGHAE/BUKPYUNG",
        "origin_country": "COREA DEL SUR",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-39",
        "name": "CARAL",
        "eta": "29/01/2026 10:00:00",
        "agency": "MARITIMA MERCANTIL",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "PLATAFORMA TERMINAL MARINO PISCO CAMISEA - CAMISEA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 182.55,
        "beam": 27.34,
        "dwt": 39480.0,
        "gross_tonnage": ""
    }
];