const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00074",
        "name": "CAP. BERNY B.",
        "eta": "02/02/2026 13:00:00",
        "agency": "DOLMAR",
        "origin_port": "EC - MANTA",
        "origin_country": "ECUADOR",
        "terminal": "BAHIA DE PAITA",
        "etb": "-",
        "type": "PESQUERO",
        "flag": "ECUADOR",
        "length": 61.12,
        "beam": 11.7,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00066",
        "name": "DEL MONTE PRIDE",
        "eta": "02/02/2026 17:00:00",
        "agency": "COSMOS",
        "origin_port": "EC - PUERTO BOLIVAR",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 192,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-66",
        "name": "DEL MONTE PRIDE",
        "eta": "02/02/2026 23:00:00",
        "agency": "COSMOS",
        "origin_port": "CR - CALDERA",
        "origin_country": "COSTA RICA",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 192,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00308",
        "name": "HOOGE",
        "eta": "02/02/2026 02:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - SAN VICENTE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "02/02/2026 04:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "ANTIGUA Y BARBUDA",
        "length": 172,
        "beam": 28.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00327",
        "name": "MORNING CORNELIA",
        "eta": "02/02/2026 05:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "02/02/2026 07:00:00",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "COREA DEL SUR",
        "length": 199.94,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00306",
        "name": "WOLVERINE",
        "eta": "02/02/2026 06:00:00",
        "agency": "TRAMARSA",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "02/02/2026 21:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.9,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00299",
        "name": "HALSTED",
        "eta": "02/02/2026 06:00:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "02/02/2026 11:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 222.15,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00256",
        "name": "GULLHOLMEN ISLAND",
        "eta": "02/02/2026 08:00:00",
        "agency": "CANOPUS",
        "origin_port": "AR - SAN LORENZO",
        "origin_country": "ARGENTINA",
        "terminal": "APM TERMINALS",
        "etb": "02/02/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "HONG KONG",
        "length": 179.97,
        "beam": 29.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00330",
        "name": "TABLONES",
        "eta": "02/02/2026 12:00:00",
        "agency": "TRANSTOTAL",
        "origin_port": "PE - SAN JUAN DE MARCONA",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 158.8,
        "beam": 22.74,
        "dwt": 16533.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00331",
        "name": "LUNITA",
        "eta": "02/02/2026 12:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "GT - PUERTO QUETZAL",
        "origin_country": "GUATEMALA",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "NORUEGA",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00220",
        "name": "MTM TORTOLA",
        "eta": "02/02/2026 15:00:00",
        "agency": "AGUNSA PERU",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "02/02/2026 17:00:00",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 149.93,
        "beam": 24.6,
        "dwt": 22396.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00287",
        "name": "BBC CAMPANA",
        "eta": "02/02/2026 16:00:00",
        "agency": "SERPAC",
        "origin_port": "PE - ILO",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "01/01/0001 00:00:00",
        "type": "GENERAL CARGO VESSEL",
        "flag": "ANTIGUA Y BARBUDA",
        "length": 138.5,
        "beam": 21,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00309",
        "name": "GUAYAQUIL EXPRESS",
        "eta": "02/02/2026 20:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "02/02/2026 23:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "ALEMANIA",
        "length": 333.18,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00273",
        "name": "HANSA NAREE",
        "eta": "02/02/2026 21:00:00",
        "agency": "SERPAC",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 179.95,
        "beam": 32.01,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00305",
        "name": "SAKURA GLORY",
        "eta": "02/02/2026 22:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "APM TERMINALS",
        "etb": "06/02/2026 18:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 189.93,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-321",
        "name": "CMA CGM ALIAGA",
        "eta": "02/02/2026 01:30:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 246.86,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-132",
        "name": "URUBAMBA",
        "eta": "02/02/2026 08:00:00",
        "agency": "RENADSA",
        "origin_port": "PE - MOLLENDO",
        "origin_country": "PERU",
        "terminal": "PETROPERU CONCHAN",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 175.98,
        "beam": 31,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-155",
        "name": "TOP GRACE",
        "eta": "02/02/2026 17:00:00",
        "agency": "RASAN",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 199.9,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-307",
        "name": "ITAJAI EXPRESS",
        "eta": "02/02/2026 18:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - IQUIQUE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 335.12,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-308",
        "name": "HOOGE",
        "eta": "02/02/2026 20:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - ANTOFAGASTA",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "ANTIGUA Y BARBUDA",
        "length": 172,
        "beam": 28.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-328",
        "name": "DATO SUCCESS",
        "eta": "02/02/2026 22:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CN - LIANYUNGANG",
        "origin_country": "CHINA",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "HONG KONG",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-302",
        "name": "GOLDEN GLORY",
        "eta": "02/02/2026 23:45:00",
        "agency": "AGUNSA PERU",
        "origin_port": "CL - QUINTERO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.98,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-53",
        "name": "JULES POINT",
        "eta": "02/02/2026 08:30:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 179.9,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-49",
        "name": "ALICANTE KNUTSEN",
        "eta": "02/02/2026 17:30:00",
        "agency": "COSMOS",
        "origin_port": "KR - GWANGYANG",
        "origin_country": "COREA DEL SUR",
        "terminal": "TP PERU LNG MELCHORITA",
        "etb": "",
        "type": "BUQUE GASERO",
        "flag": "FRANCIA",
        "length": 298.98,
        "beam": 46.4,
        "dwt": 95548.0,
        "gross_tonnage": ""
    }
];