const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00060",
        "name": "RICKY A",
        "eta": "26/01/2026 07:00:00",
        "agency": "DOLMAR",
        "origin_port": "EC - POSORJA",
        "origin_country": "ECUADOR",
        "terminal": "BAHIA DE PAITA",
        "etb": "-",
        "type": "PESQUERO",
        "flag": "ECUADOR",
        "length": 67.3,
        "beam": 11,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-58",
        "name": "CAPE SCOTT",
        "eta": "26/01/2026 08:00:00",
        "agency": "TRAMARSA",
        "origin_port": "EC - POSORJA",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "PORTUGAL",
        "length": 188.8,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-60",
        "name": "RICKY A",
        "eta": "26/01/2026 10:30:00",
        "agency": "DOLMAR",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "BAHIA DE PAITA",
        "etb": "",
        "type": "PESQUERO",
        "flag": "ECUADOR",
        "length": 67.3,
        "beam": 11,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00152",
        "name": "SEABOARD VICTORY",
        "eta": "26/01/2026 00:15:00",
        "agency": "CITIKOLD",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "DP WORLD",
        "etb": "26/01/2026 03:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 248,
        "beam": 35.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00179",
        "name": "JULES POINT",
        "eta": "26/01/2026 06:00:00",
        "agency": "CANOPUS",
        "origin_port": "PE - SALAVERRY",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 179.9,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00213",
        "name": "BELKNIGHT",
        "eta": "26/01/2026 12:00:00",
        "agency": "RENADSA",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "NORUEGA",
        "length": 199.9,
        "beam": 32.25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00167",
        "name": "DIGNITY LEADER",
        "eta": "26/01/2026 13:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "26/01/2026 14:00:00",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "BAHAMAS",
        "length": 199.95,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00259",
        "name": "CMA CGM TAGE",
        "eta": "26/01/2026 14:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "26/01/2026 15:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 299.95,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00194",
        "name": "CHIPOL HUANGHE",
        "eta": "26/01/2026 15:00:00",
        "agency": "TRANSTOTAL",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "01/01/0001 00:00:00",
        "type": "GENERAL CARGO VESSEL",
        "flag": "HONG KONG",
        "length": 188.34,
        "beam": 27.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00231",
        "name": "CMA CGM CARL ANTOINE",
        "eta": "26/01/2026 23:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 299.9,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-121",
        "name": "BBC TEXAS",
        "eta": "26/01/2026 05:00:00",
        "agency": "SERPAC",
        "origin_port": "PE - ILO",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "GENERAL CARGO VESSEL",
        "flag": "ANTIGUA Y BARBUDA",
        "length": 138.16,
        "beam": 21,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-221",
        "name": "CHEMROAD SEA",
        "eta": "26/01/2026 06:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "CL - MEJILLONES",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PANAMA",
        "length": 170.17,
        "beam": 26.6,
        "dwt": 33560.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-237",
        "name": "MANZANILLO EXPRESS",
        "eta": "26/01/2026 16:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - IQUIQUE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335.12,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-238",
        "name": "LITTLE GRACE",
        "eta": "26/01/2026 17:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - ANTOFAGASTA",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 171.9,
        "beam": 28.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-233",
        "name": "DARYA RADHE",
        "eta": "26/01/2026 20:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CN - QINGDAO",
        "origin_country": "CHINA",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "ISLAS MARSHALL",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-230",
        "name": "ELITE FAITH",
        "eta": "26/01/2026 20:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "GENERAL CARGO VESSEL",
        "flag": "PANAMA",
        "length": 122.2,
        "beam": 19.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00045",
        "name": "ZOILO",
        "eta": "26/01/2026 16:00:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - MOLLENDO",
        "origin_country": "PERU",
        "terminal": "PLATAFORMA TERMINAL MARINO PISCO CAMISEA - CAMISEA",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "MALTA",
        "length": 183.12,
        "beam": 32.2,
        "dwt": 49990.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-38",
        "name": "MORNING LADY",
        "eta": "26/01/2026 02:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "KR - ULSAN",
        "origin_country": "COREA DEL SUR",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "COREA DEL SUR",
        "length": 232.38,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-44",
        "name": "GOLDEN VOYAGER",
        "eta": "26/01/2026 20:00:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "PLATAFORMA TERMINAL MARINO PISCO CAMISEA - CAMISEA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PANAMA",
        "length": 183.07,
        "beam": 32.2,
        "dwt": 49999.0,
        "gross_tonnage": ""
    }
];