
server {
    listen 80;
    server_name petral.geeksoft.tech;

    root /var/www/html/petral;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Logging
    access_log /var/log/nginx/petral_access.log;
    error_log /var/log/nginx/petral_error.log;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
