const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00095",
        "name": "SEABOARD VALOR",
        "eta": "11/02/2026 14:00:00",
        "agency": "CITIKOLD",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 248,
        "beam": 35.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-91",
        "name": "CMA CGM IMAGINATION",
        "eta": "11/02/2026 12:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "EC - POSORJA",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 272.3,
        "beam": 42.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-95",
        "name": "SEABOARD VALOR",
        "eta": "11/02/2026 23:00:00",
        "agency": "CITIKOLD",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 248,
        "beam": 35.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECHM",
        "movement_type": "DEPARTURE",
        "due": "CHM-2026-24",
        "name": "IMARPE V",
        "eta": "11/02/2026 12:00:00",
        "agency": "IMARPE",
        "origin_port": "PE - NATIONAL WATERS",
        "origin_country": "PERU",
        "terminal": "ENAPU",
        "etb": "",
        "type": "CIENT\u00cdFICO",
        "flag": "PERU",
        "length": 16.6,
        "beam": 5.25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00408",
        "name": "CMA CGM ALIAGA",
        "eta": "11/02/2026 00:01:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 246.86,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00398",
        "name": "SETO HARMONY",
        "eta": "11/02/2026 01:00:00",
        "agency": "TRANSTOTAL",
        "origin_port": "MX - MANZANILLO",
        "origin_country": "MEXICO",
        "terminal": "APM TERMINALS",
        "etb": "16/02/2026 07:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 182.87,
        "beam": 31,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00392",
        "name": "DOVER",
        "eta": "11/02/2026 08:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CA - VANCOUVER",
        "origin_country": "CANADA",
        "terminal": "APM TERMINALS",
        "etb": "11/02/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "MALTA",
        "length": 196.44,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00062",
        "name": "OSPREY",
        "eta": "11/02/2026 09:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - BARQUITO",
        "origin_country": "CHILE",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "11/02/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "CHIPRE",
        "length": 199.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00427",
        "name": "MANTARO",
        "eta": "11/02/2026 11:30:00",
        "agency": "RENADSA",
        "origin_port": "PE - SUPE",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 183,
        "beam": 32.2,
        "dwt": 51393.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00269",
        "name": "AS FELICIA",
        "eta": "11/02/2026 12:00:00",
        "agency": "COSMOS",
        "origin_port": "JM - KINGSTON",
        "origin_country": "JAMAICA",
        "terminal": "DP WORLD",
        "etb": "11/02/2026 14:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "PORTUGAL",
        "length": 166.15,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00413",
        "name": "ALIOTH",
        "eta": "11/02/2026 13:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "12/02/2026 11:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 161.3,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00311",
        "name": "MSC LELLA",
        "eta": "11/02/2026 15:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "11/02/2026 16:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 365.98,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00416",
        "name": "MOQUEGUA",
        "eta": "11/02/2026 17:00:00",
        "agency": "TRANSTOTAL",
        "origin_port": "PE - SAN JUAN DE MARCONA",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "11/02/2026 23:00:00",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 134.16,
        "beam": 20.5,
        "dwt": 14298.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00380",
        "name": "GLOBAL LEADER",
        "eta": "11/02/2026 20:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "JP - YOKOHAMA",
        "origin_country": "JAPON",
        "terminal": "APM TERMINALS",
        "etb": "12/02/2026 07:00:00",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "BAHAMAS",
        "length": 189.2,
        "beam": 32.25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00320",
        "name": "IWAGI ISLAND",
        "eta": "11/02/2026 23:00:00",
        "agency": "MARITIMA MERCANTIL",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "APM TERMINALS",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 179.97,
        "beam": 29.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-364",
        "name": "SEA VOYAGER",
        "eta": "11/02/2026 07:30:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - PUERTO ANGAMOS",
        "origin_country": "CHILE",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2023-3013",
        "name": "FREDDIE B",
        "eta": "11/02/2026 10:00:00",
        "agency": "AERODOC S.A.C.",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "YACHT CLUB",
        "etb": "",
        "type": "NAVES DEPORTIVAS Y DE RECREO",
        "flag": "POLONIA",
        "length": 13.95,
        "beam": 4.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-408",
        "name": "CMA CGM ALIAGA",
        "eta": "11/02/2026 12:30:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 246.86,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-261",
        "name": "MACAW ARROW",
        "eta": "11/02/2026 18:00:00",
        "agency": "TRANSTOTAL",
        "origin_port": "CL - CORONEL",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "GENERAL CARGO VESSEL",
        "flag": "NORUEGA",
        "length": 209.99,
        "beam": 36,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2025-3502",
        "name": "CAMISEA",
        "eta": "11/02/2026 23:00:00",
        "agency": "RENADSA",
        "origin_port": "PA - BALBOA",
        "origin_country": "PANAMA",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 183.4,
        "beam": 32,
        "dwt": 44577.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00071",
        "name": "BBC NEWCASTLE",
        "eta": "11/02/2026 08:00:00",
        "agency": "SERPAC",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "GENERAL CARGO VESSEL",
        "flag": "ANTIGUA Y BARBUDA",
        "length": 132.2,
        "beam": 15.87,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00073",
        "name": "GENCO WASP",
        "eta": "11/02/2026 12:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "TPP SA",
        "etb": "01/01/0001 00:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "ISLAS MARSHALL",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-68",
        "name": "MSC PISA",
        "eta": "11/02/2026 20:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335,
        "beam": 45.6,
        "dwt": 0,
        "gross_tonnage": ""
    }
];