const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-82",
        "name": "SWEDISH STREAM",
        "eta": "05/02/2026 05:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "US - GLOUCESTER",
        "origin_country": "ESTADOS UNIDOS",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "BAHAMAS",
        "length": 158.13,
        "beam": 24.43,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-86",
        "name": "ARSOS",
        "eta": "05/02/2026 06:00:00",
        "agency": "CITIKOLD",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "CHIPRE",
        "length": 166.15,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-81",
        "name": "CENA FAITH",
        "eta": "05/02/2026 22:00:00",
        "agency": "COSMOS",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "GENERAL CARGO VESSEL",
        "flag": "PANAMA",
        "length": 122.2,
        "beam": 19.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00348",
        "name": "MAERSK REDWOOD",
        "eta": "05/02/2026 02:30:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "05/02/2026 04:30:00",
        "type": "BUQUE CONTAINERO",
        "flag": "SINGAPORE",
        "length": 200,
        "beam": 36.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00340",
        "name": "VECCO",
        "eta": "05/02/2026 03:20:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - ANTOFAGASTA",
        "origin_country": "CHILE",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "BAHAMAS",
        "length": 179.9,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00294",
        "name": "AMBER CONFIDENCE",
        "eta": "05/02/2026 06:00:00",
        "agency": "TRAMARSA",
        "origin_port": "AR - SAN LORENZO",
        "origin_country": "ARGENTINA",
        "terminal": "APM TERMINALS",
        "etb": "-",
        "type": "GENERAL CARGO VESSEL",
        "flag": "PORTUGAL",
        "length": 179.97,
        "beam": 29.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00364",
        "name": "SEA VOYAGER",
        "eta": "05/02/2026 07:30:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - PISCO",
        "origin_country": "PERU",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "05/02/2026 15:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00323",
        "name": "ONE SERENITY",
        "eta": "05/02/2026 11:30:00",
        "agency": "MERCATOR",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "DP WORLD",
        "etb": "05/02/2026 13:30:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335.94,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00354",
        "name": "THOMAS B",
        "eta": "05/02/2026 14:00:00",
        "agency": "MARITIMA MERCANTIL",
        "origin_port": "PE - ILO",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "08/02/2026 23:00:00",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 149.95,
        "beam": 23.2,
        "dwt": 19992.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00279",
        "name": "LUNA DISCOVERY",
        "eta": "05/02/2026 15:00:00",
        "agency": "CANOPUS",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "08/02/2026 23:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "ISLAS MARSHALL",
        "length": 186.4,
        "beam": 27.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-332",
        "name": "MOCHE",
        "eta": "05/02/2026 09:00:00",
        "agency": "RENADSA",
        "origin_port": "PE - TALARA",
        "origin_country": "PERU",
        "terminal": "PETROPERU CONCHAN",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 175.93,
        "beam": 31,
        "dwt": 39999.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-264",
        "name": "OCEAN AMBITIOUS",
        "eta": "05/02/2026 12:00:00",
        "agency": "AGUNSA PERU",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "HONG KONG",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-220",
        "name": "MTM TORTOLA",
        "eta": "05/02/2026 14:00:00",
        "agency": "AGUNSA PERU",
        "origin_port": "CL - CALBUCO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 149.93,
        "beam": 24.6,
        "dwt": 22396.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-357",
        "name": "MEDKON DON",
        "eta": "05/02/2026 16:00:00",
        "agency": "COSCO",
        "origin_port": "CL - IQUIQUE",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "PANAMA",
        "length": 147.87,
        "beam": 23.25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-253",
        "name": "STENA IMPERIAL",
        "eta": "05/02/2026 20:00:00",
        "agency": "COSMOS",
        "origin_port": "US - CORPUS CHRISTI",
        "origin_country": "ESTADOS UNIDOS",
        "terminal": "VALERO PER\u00da",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "MALTA",
        "length": 183.17,
        "beam": 32.26,
        "dwt": 49750.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-348",
        "name": "MAERSK REDWOOD",
        "eta": "05/02/2026 21:00:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "SINGAPORE",
        "length": 200,
        "beam": 36.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-336",
        "name": "TOUBKAL PARK",
        "eta": "05/02/2026 23:00:00",
        "agency": "RENADSA",
        "origin_port": "EC - MANTA",
        "origin_country": "ECUADOR",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "LIBERIA",
        "length": 146.5,
        "beam": 24,
        "dwt": 19971.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00063",
        "name": "ML FREGATA",
        "eta": "05/02/2026 23:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-55",
        "name": "MSC SERENA",
        "eta": "05/02/2026 18:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335,
        "beam": 45.6,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-50",
        "name": "SEA GOAT",
        "eta": "05/02/2026 23:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 182.9,
        "beam": 31.6,
        "dwt": 0,
        "gross_tonnage": ""
    }
];