const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00087",
        "name": "MSC SERENA",
        "eta": "08/02/2026 05:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "PE - CALLAO",
        "origin_country": "PERU",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335,
        "beam": 45.6,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "ARRIVAL",
        "due": "PAI-2026-00021",
        "name": "HOOD ISLAND",
        "eta": "08/02/2026 07:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "-",
        "type": "FRIGORIFICO",
        "flag": "BAHAMAS",
        "length": 179.9,
        "beam": 25.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-94",
        "name": "IMARPE V",
        "eta": "08/02/2026 00:10:00",
        "agency": "IMARPE",
        "origin_port": "PE - NATIONAL WATERS",
        "origin_country": "PERU",
        "terminal": "BAHIA DE PAITA",
        "etb": "",
        "type": "CIENT\u00cdFICO",
        "flag": "PERU",
        "length": 16.6,
        "beam": 5.25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-87",
        "name": "MSC SERENA",
        "eta": "08/02/2026 16:30:00",
        "agency": "MSC DEL PERU",
        "origin_port": "PA - RODMAN",
        "origin_country": "PANAMA",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 335,
        "beam": 45.6,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-21",
        "name": "HOOD ISLAND",
        "eta": "08/02/2026 23:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "GB - DOVER",
        "origin_country": "REINO UNIDO",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "FRIGORIFICO",
        "flag": "BAHAMAS",
        "length": 179.9,
        "beam": 25.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00371",
        "name": "MAERSK TOKYO",
        "eta": "08/02/2026 00:30:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - PISCO",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 175.3,
        "beam": 32.22,
        "dwt": 44994.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00355",
        "name": "NORDIC AMI",
        "eta": "08/02/2026 05:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "08/02/2026 08:00:00",
        "type": "BUQUE TANQUE",
        "flag": "LIBERIA",
        "length": 158.03,
        "beam": 22,
        "dwt": 16240.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00343",
        "name": "RIO DE JANEIRO EXPRESS",
        "eta": "08/02/2026 05:00:00",
        "agency": "TRAMARSA",
        "origin_port": "MX - LAZARO CARDENAS",
        "origin_country": "MEXICO",
        "terminal": "DP WORLD",
        "etb": "08/02/2026 08:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "ALEMANIA",
        "length": 335.12,
        "beam": 51.05,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00368",
        "name": "CAPE HELLAS",
        "eta": "08/02/2026 09:00:00",
        "agency": "MERCATOR",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 186,
        "beam": 34.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00344",
        "name": "LITTLE GRACE",
        "eta": "08/02/2026 12:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - SAN VICENTE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "09/02/2026 02:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 171.9,
        "beam": 28.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00120",
        "name": "WESTERN STABAEK",
        "eta": "08/02/2026 13:30:00",
        "agency": "RENADSA",
        "origin_port": "CL - MEJILLONES",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "FILIPINAS",
        "length": 179.9,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00383",
        "name": "KOUSHUN",
        "eta": "08/02/2026 15:00:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - SALAVERRY",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "01/01/0001 00:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00401",
        "name": "ECO MARIN",
        "eta": "08/02/2026 17:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "08/02/2026 18:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 148,
        "beam": 27.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00197",
        "name": "MSC ELENOIRE",
        "eta": "08/02/2026 19:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "08/02/2026 21:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 366,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00385",
        "name": "KAPRIJKE",
        "eta": "08/02/2026 20:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "CL - MEJILLONES",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GASERO",
        "flag": "BELGICA",
        "length": 181.7,
        "beam": 29.4,
        "dwt": 29639.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00319",
        "name": "MSC OLIA",
        "eta": "08/02/2026 20:30:00",
        "agency": "MSC DEL PERU",
        "origin_port": "KR - BUSAN",
        "origin_country": "COREA DEL SUR",
        "terminal": "APM TERMINALS",
        "etb": "08/02/2026 23:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 231,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00361",
        "name": "CLIFFORD MAERSK",
        "eta": "08/02/2026 21:00:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "08/02/2026 22:30:00",
        "type": "BUQUE CONTAINERO",
        "flag": "DINAMARCA",
        "length": 346.98,
        "beam": 42.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-00297",
        "name": "SEABOARD VALOR",
        "eta": "08/02/2026 23:30:00",
        "agency": "CITIKOLD",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "DP WORLD",
        "etb": "09/02/2026 11:45:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 248,
        "beam": 35.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-350",
        "name": "SEAWAYS KENOSHA",
        "eta": "08/02/2026 01:30:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - MOLLENDO",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "",
        "type": "BUQUE TANQUE QUIMIQUERO",
        "flag": "LIBERIA",
        "length": 183,
        "beam": 32.2,
        "dwt": 50082.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-382",
        "name": "URUBAMBA",
        "eta": "08/02/2026 03:00:00",
        "agency": "RENADSA",
        "origin_port": "PE - TALARA",
        "origin_country": "PERU",
        "terminal": "PETROPERU CONCHAN",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PERU",
        "length": 175.98,
        "beam": 31,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-360",
        "name": "WAN HAI 613",
        "eta": "08/02/2026 04:15:00",
        "agency": "TRANSTOTAL",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 284.71,
        "beam": 40,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-390",
        "name": "CENA FAITH",
        "eta": "08/02/2026 07:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "",
        "type": "GENERAL CARGO VESSEL",
        "flag": "PANAMA",
        "length": 122.2,
        "beam": 19.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-358",
        "name": "SEA GOAT",
        "eta": "08/02/2026 14:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - PUNTA LOBITOS",
        "origin_country": "PERU",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 182.9,
        "beam": 31.6,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-371",
        "name": "MAERSK TOKYO",
        "eta": "08/02/2026 14:10:00",
        "agency": "ISS MARINE",
        "origin_port": "JP - KAWASAKI",
        "origin_country": "JAPON",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 175.3,
        "beam": 32.22,
        "dwt": 44994.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-234",
        "name": "HONEY ISLAND",
        "eta": "08/02/2026 14:15:00",
        "agency": "RASAN",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "SINGAPORE",
        "length": 189.99,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-316",
        "name": "GLOVIS SUCCESS",
        "eta": "08/02/2026 14:45:00",
        "agency": "AGUNSA PERU",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "LIBERIA",
        "length": 199.9,
        "beam": 38,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-199",
        "name": "MSC CASSANDRE",
        "eta": "08/02/2026 15:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 328.46,
        "beam": 48.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-275",
        "name": "MORNING SPARROW",
        "eta": "08/02/2026 20:00:00",
        "agency": "COSMOS",
        "origin_port": "PE - PISCO",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "LIBERIA",
        "length": 185.99,
        "beam": 32.23,
        "dwt": 49997.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-280",
        "name": "SUMIYOSHI MARU NO.75",
        "eta": "08/02/2026 22:00:00",
        "agency": "GYOREN",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "PESQUERO",
        "flag": "JAPON",
        "length": 51.32,
        "beam": 9.1,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-346",
        "name": "GARNET LEADER",
        "eta": "08/02/2026 23:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE ROLL ON \u0096 ROLL OFF",
        "flag": "BAHAMAS",
        "length": 199.98,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-368",
        "name": "CAPE HELLAS",
        "eta": "08/02/2026 23:00:00",
        "agency": "MERCATOR",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 186,
        "beam": 34.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-333",
        "name": "MOCKINGBIRD",
        "eta": "08/02/2026 23:00:00",
        "agency": "RENADSA",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "TRALSA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 146.5,
        "beam": 24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00057",
        "name": "MAERSK BINTAN",
        "eta": "08/02/2026 17:00:00",
        "agency": "IAN TAYLOR  S.A.C",
        "origin_port": "CL - VALPARAISO",
        "origin_country": "CHILE",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "HONG KONG",
        "length": 223.3,
        "beam": 32.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-64",
        "name": "ANTHEIA",
        "eta": "08/02/2026 11:30:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TPP SA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "MALTA",
        "length": 168.58,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    }
];